version: '3.7'

services:
    mongodb:
        image: mongo:latest
        container_name: mongodb
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: admin
            MONGO_INITDB_ROOT_PASSWORD: admin
            MONGO_INITDB_DATABASE: GameStore
        ports:
            - "27017:27017"
        volumes:
            - ./db/:/docker-entrypoint-initdb.d/:ro

    backend:
        build: .
        container_name: backend
        restart: always
        ports:
            - "5000:5000"
        profiles:
            - prod
        depends_on:
            - mongodb
        volumes:
            - .:/app:ro
